### ISSUE TITLE
Unable to login/query for records

### ISSUE THREAD

**Issue by spearmootz** [Luidog/fms-api-client#24]
**Describe the bug**
Im getting a couple of issues when using this library. related to login in, and response handling.

I tried Filemaker.create to get a client but it wouldnt work, so i consoled Filemaker as well as the code and thought it was a class so i started using new which sort of worked.

in regards to login in, the preinit hook is not being triggered, so when i try to query it says that this.connection.valid is not a function.

if i call preinit manually and then try to query, i get a response saying
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>400 Bad Request</title>\n</head><body>\n<h1>Bad Request</h1>\n<p>Your browser sent a request that this server could not understand.<br />\n</p>\n<hr>\n<address>Apache/2.4.27 (Win64) PHP/5.6.31 Server at localhost Port 80</address>\n</body></html>\n

**Expected behavior**
I am able to query for records.

**Code Examples**
import { connect } from 'marpat';
import { Filemaker } from 'fms-api-client';

connect('nedb://memory')
  .then(() => new Filemaker(credentials))
  .then(client => {
    const getRecordsToProcess = () => client.list(patientsLayout, {});

    client.preInit(credentials);
    getRecordsToProcess().then(console.log);
  });

**Tests**
If possible write a failing test that showcases the bug.

**Additional context**
I saw that you have several test for this package and that its running correctly, i tried to look at the test to see what i was doing wrong but i couldnt figure it out:(

**Comment by Luidog** [comment]
Hey @spearmootz, thanks for giving fms-api-client a try! 

Sorry you were not able to get it to work for you. It looks like you called the datastore (what you import as Filemaker) directly. This most likely where the issue occurred. 

You should not use new nor call the preInit function. You should use FileMaker.create() which will create a new client for you and call the preInit function.  Check out the example here:

https://github.com/Luidog/fms-api-client/blob/bad0c68e52b454d89fff7d461603832ee2b8a0be/examples/index.js#L42

Note that in the example that a client is created and then saved using `const client = Filemaker.create(credentials) client.save().then(client=>client)`

The client must be created and saved before it is used. to recall the client you can use FileMaker.findOne() or Fileamaker.find(query) which either produce null or a client. An example:

`Filemaker.findOne().then(client=>client ? client.list('patientLayout') : null).then(response=>console.log(response))`

I am going to close this issue since the client is 100% tested. If you run into any more issues please just create a new one. I hope this helps.

**Comment by spearmootz** [comment]
ok, i changed the code and am using Filemaker.create and the save but i am still having issues querying.

Im logging out the response that the client gets and i saw that this is the request is making. i tested in postman, using the same auth token that the library generated, it worked on postman but not in the client.

any last suggestions?

POST HOST/fmi/data/v1/databases/CORRECTAPPLICATION/sessions HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json\r\nauthorization: Basic ENCODEDCREDENTIALS\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 2\r\nHost: localhost\r\nConnection: close\r\n\r\n

**Comment by Luidog** [comment]
@spearmootz, Can you please post a gist of your code. It is impossible to help without them. As the client is fully tested there really shouldn't be any issues using it outside of unclear examples. Examples of how you are trying to use it will help me be more clear in the documentation moving forward.

**Comment by spearmootz** [comment]
soo...... the configuration.server has to be a fully URL. so it must include http:// or https://

**Comment by Luidog** [comment]
Ah good catch! I should add some verification to the client server. Thank You! Let me know your experiences with the client after you have used it a bit. I am always looking for good feedback.

**Comment by spearmootz** [comment]
so far, its pretty solid. i had vetted the code weeks ago and it looked pretty great. 

i was really surprised when i couldnt get it working, but it was a minor issue.
