### ISSUE TITLE
Opening Multiple FM Data API Sessions

### ISSUE THREAD

**Issue by havi-b** [Luidog/fms-api-client#65]
**Describe the bug**
Multiple FM Data API Session create for each Client Object.
Number of sessions > concurrency

**Expected behavior**
Maximum number of sessions should be <= concurrency.

**Code Examples**
```
router.post('/login', (req, res) => {

  // FM Config

  let config = {
    name: `${Date.now()} ${req.body.user}`,
    database: req.body.db,
    concurrency: req.body.concurrency || 2,
    server: req.body.server,
    user: req.body.user,
    password: req.body.pswd,
    usage: true,
    timeout: 1000 * 60 * 2 // 2 Minutes
  };

  connect('nedb://memory')
    .then(db => {
      // Create Client
      const FM = Filemaker.create(config);
      return FM.save();
    })
    .then(client => {
      // Login using new client object
      client
        .login(result => result)
        .then(result => {
      // Create "Token"
          let hash = crypto
            .createHash('sha256')
            .update(`${Date.now()} ${req.body.user}`)
            .digest('hex');
      // Store Client Object in a local object with the "Token" as the key. Then send the requesting client the "Token"
          clientPool[hash] = client;
          res.send({
            client,
            hash
          });
        })
        .catch(err => {
          console.log(err);
          res.status(400).send(err);
        });
    })
    .catch(err => {
      console.log('Marpat Error: ' + err);
      res.status(400).send(err);
    });
});
```

**Additional context**
I created a nodejs "Micro-service" to facilitate interaction between FM and React Native. In order to handle multiple different users/connections I created the endpoint above.

The idea was that the user would send their credentials and the service would create a unique hash which would serve as sort of a token. It then stores the Client object as the value in a local JS object with the token as the key.

Everything seems to work as expected, however, when one or multiple client objects are used to call any of the fms-api-client methods there is 40+ Data API sessions opened. On the FM Server Console it shows that each one of the users spawns multiple sessions even if only one user's client object was used.

What am I doing wrong?

**Comment by Luidog** [comment]
Thank you for reaching out. I appreciate the example you provided. It is beneficial. In the example, the [marpat function connect](https://github.com/Luidog/marpat#connect-to-the-database) is called each time the router.post method is triggered. While the connect function can be called multiple times, it is best practice to only call it once. This approach is similar to connecting to other data stores.

I recommend calling the connect method before listening with for incoming requests:

```javascript
const express = require("express");
const { connect } = require("marpat");
const app = express();
const port = 3000;

connect("nedb://memory").then(db =>
    app.listen(port, () => console.log(`Example app listening on port ${port}!`))
);
```
Once connected to a data store, you can perform a query using the find or findOne methods: 

```javascript
const { Router } = require("express");
const { Filemaker } = require("fms-api-client");

const route = new Router();

route.post("/:id", (req, res) =>
  Filemaker.find({ _id: req.params.id }).then(client =>
    client
      ? res.status(200).json(client)
      : res.status(404).json({ message: "no client with that id" })
  )
);
```

A good strategy is to embed an id inside JWT and then using that id in a query to retrieve the client. I have found that a good plan is to insert an id inside jwt token and then to use that id in a query to retrieve the client.

As it turns out - marpat supports a variety of datastores. The in-memory datastore `nedb://memory` is not persistent. Each time the process is restarted, the current datastore's information is destroyed. This behavior can lead to a large number of sessions being started on your FileMaker Server. I recommend using persistent storage setting such as Filesystem storage`nedb://dapi` or for scalability MongoDB storage `mongodb://....`.

I have found a beneficial strategy is to embed query parameters into JWTs and using those JWTs to find and use Data API clients.

I have published two projects you might find helpful: the [big-brother](https://github.com/Luidog/big-brother) project and the [modular-filemaker](https://github.com/modularfilemaker/mfm-api) project. Please reach out if you have additional questions.

As I don't believe this is an issue with the project, I am going to close this issue. Please reopen the issue if you have additional questions.
