### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by spearmootz** [Luidog/fms-api-client#77]
having issues with FM here.  I was just wondering, what kind of performance would you say you can get inserting minimal data into FM through api.

i have a minimal solution and code, and i try to insert 100k records.  It starts insering at 30 per sec, and then it drops to about 13 after 4k records and eventually it drops to like 4 per second.  in your experience, is this normal?

**Comment by Luidog** [comment]
Hey @spearmootz. My experience leads me to believe that slowness has more to do with the server FMS is running on rather than FMS itself. I have seen FMS slow down when there are >100k records with wide tables. 

If you do more research and have data points to refer to I would be very interested in hearing them.

**Comment by spearmootz** [comment]
the experience that we hare having is a table, with 4 fields. the server has 8 cores, disk queues metric is less than 0.1, 10+ gigs of free memory ram.

i do see that when the sessions are restarted it picks up to 80 again and that i can make multiple sessions and each follows the same behavior.
